- hosts: all
  become: true
  vars:
    remote_user_name: devops

  tasks:
  - name: Create new user on managed node
    user:
      name: "{{ remote_user_name }}"
      groups: sudo
      append: yes

  - name: Add sudo entries for new user
    copy:
      content: "{{ remote_user_name }} ALL=(ALL) NOPASSWD: ALL"
      dest: "/etc/sudoers.d/{{ remote_user_name }}"
      mode: '0440'

  - name: Configure Hostname
    hostname:
      name: "{{ inventory_hostname }}"
